#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Commands\Money\GenerateMoneyStaticHelper;
use Commands\Money\GenerateMoneyStaticTrait;

$application = new Application();
$application->add(new GenerateMoneyStaticHelper());
$application->add(new GenerateMoneyStaticTrait());
$application->run();
