#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Commands\Money\GenerateDocMoneyStatic;

$application = new Application();
$application->add(new GenerateDocMoneyStatic());
$application->run();
