<?php

namespace Money;

/**
 * This is a generated file. Do not edit it manually!
 *
 * @method static MoneyRange AED(string $amount)
 * @method static MoneyRange ALL(string $amount)
 * @method static MoneyRange AMD(string $amount)
 * @method static MoneyRange ANG(string $amount)
 * @method static MoneyRange AOA(string $amount)
 * @method static MoneyRange ARS(string $amount)
 * @method static MoneyRange AUD(string $amount)
 * @method static MoneyRange AWG(string $amount)
 * @method static MoneyRange AZN(string $amount)
 * @method static MoneyRange BAM(string $amount)
 * @method static MoneyRange BBD(string $amount)
 * @method static MoneyRange BDT(string $amount)
 * @method static MoneyRange BGN(string $amount)
 * @method static MoneyRange BHD(string $amount)
 * @method static MoneyRange BIF(string $amount)
 * @method static MoneyRange BMD(string $amount)
 * @method static MoneyRange BND(string $amount)
 * @method static MoneyRange BOB(string $amount)
 * @method static MoneyRange BOV(string $amount)
 * @method static MoneyRange BRL(string $amount)
 * @method static MoneyRange BSD(string $amount)
 * @method static MoneyRange BTN(string $amount)
 * @method static MoneyRange BWP(string $amount)
 * @method static MoneyRange BYN(string $amount)
 * @method static MoneyRange BZD(string $amount)
 * @method static MoneyRange CAD(string $amount)
 * @method static MoneyRange CDF(string $amount)
 * @method static MoneyRange CHE(string $amount)
 * @method static MoneyRange CHF(string $amount)
 * @method static MoneyRange CHW(string $amount)
 * @method static MoneyRange CLF(string $amount)
 * @method static MoneyRange CLP(string $amount)
 * @method static MoneyRange CNY(string $amount)
 * @method static MoneyRange COP(string $amount)
 * @method static MoneyRange COU(string $amount)
 * @method static MoneyRange CRC(string $amount)
 * @method static MoneyRange CUC(string $amount)
 * @method static MoneyRange CUP(string $amount)
 * @method static MoneyRange CVE(string $amount)
 * @method static MoneyRange CZK(string $amount)
 * @method static MoneyRange DJF(string $amount)
 * @method static MoneyRange DKK(string $amount)
 * @method static MoneyRange DOP(string $amount)
 * @method static MoneyRange DZD(string $amount)
 * @method static MoneyRange EGP(string $amount)
 * @method static MoneyRange ERN(string $amount)
 * @method static MoneyRange ETB(string $amount)
 * @method static MoneyRange EUR(string $amount)
 * @method static MoneyRange FJD(string $amount)
 * @method static MoneyRange FKP(string $amount)
 * @method static MoneyRange GBP(string $amount)
 * @method static MoneyRange GEL(string $amount)
 * @method static MoneyRange GHS(string $amount)
 * @method static MoneyRange GIP(string $amount)
 * @method static MoneyRange GMD(string $amount)
 * @method static MoneyRange GNF(string $amount)
 * @method static MoneyRange GTQ(string $amount)
 * @method static MoneyRange GYD(string $amount)
 * @method static MoneyRange HKD(string $amount)
 * @method static MoneyRange HNL(string $amount)
 * @method static MoneyRange HRK(string $amount)
 * @method static MoneyRange HTG(string $amount)
 * @method static MoneyRange HUF(string $amount)
 * @method static MoneyRange IDR(string $amount)
 * @method static MoneyRange ILS(string $amount)
 * @method static MoneyRange INR(string $amount)
 * @method static MoneyRange IQD(string $amount)
 * @method static MoneyRange IRR(string $amount)
 * @method static MoneyRange ISK(string $amount)
 * @method static MoneyRange JMD(string $amount)
 * @method static MoneyRange JOD(string $amount)
 * @method static MoneyRange JPY(string $amount)
 * @method static MoneyRange KES(string $amount)
 * @method static MoneyRange KGS(string $amount)
 * @method static MoneyRange KHR(string $amount)
 * @method static MoneyRange KMF(string $amount)
 * @method static MoneyRange KPW(string $amount)
 * @method static MoneyRange KRW(string $amount)
 * @method static MoneyRange KWD(string $amount)
 * @method static MoneyRange KYD(string $amount)
 * @method static MoneyRange KZT(string $amount)
 * @method static MoneyRange LAK(string $amount)
 * @method static MoneyRange LBP(string $amount)
 * @method static MoneyRange LKR(string $amount)
 * @method static MoneyRange LRD(string $amount)
 * @method static MoneyRange LSL(string $amount)
 * @method static MoneyRange LYD(string $amount)
 * @method static MoneyRange MAD(string $amount)
 * @method static MoneyRange MDL(string $amount)
 * @method static MoneyRange MGA(string $amount)
 * @method static MoneyRange MKD(string $amount)
 * @method static MoneyRange MMK(string $amount)
 * @method static MoneyRange MNT(string $amount)
 * @method static MoneyRange MOP(string $amount)
 * @method static MoneyRange MRU(string $amount)
 * @method static MoneyRange MUR(string $amount)
 * @method static MoneyRange MVR(string $amount)
 * @method static MoneyRange MWK(string $amount)
 * @method static MoneyRange MXN(string $amount)
 * @method static MoneyRange MXV(string $amount)
 * @method static MoneyRange MYR(string $amount)
 * @method static MoneyRange MZN(string $amount)
 * @method static MoneyRange NAD(string $amount)
 * @method static MoneyRange NGN(string $amount)
 * @method static MoneyRange NIO(string $amount)
 * @method static MoneyRange NOK(string $amount)
 * @method static MoneyRange NPR(string $amount)
 * @method static MoneyRange NZD(string $amount)
 * @method static MoneyRange OMR(string $amount)
 * @method static MoneyRange PAB(string $amount)
 * @method static MoneyRange PEN(string $amount)
 * @method static MoneyRange PGK(string $amount)
 * @method static MoneyRange PHP(string $amount)
 * @method static MoneyRange PKR(string $amount)
 * @method static MoneyRange PLN(string $amount)
 * @method static MoneyRange PYG(string $amount)
 * @method static MoneyRange QAR(string $amount)
 * @method static MoneyRange RON(string $amount)
 * @method static MoneyRange RSD(string $amount)
 * @method static MoneyRange RUB(string $amount)
 * @method static MoneyRange RWF(string $amount)
 * @method static MoneyRange SAR(string $amount)
 * @method static MoneyRange SBD(string $amount)
 * @method static MoneyRange SCR(string $amount)
 * @method static MoneyRange SDG(string $amount)
 * @method static MoneyRange SEK(string $amount)
 * @method static MoneyRange SGD(string $amount)
 * @method static MoneyRange SHP(string $amount)
 * @method static MoneyRange SLL(string $amount)
 * @method static MoneyRange SOS(string $amount)
 * @method static MoneyRange SRD(string $amount)
 * @method static MoneyRange SSP(string $amount)
 * @method static MoneyRange STN(string $amount)
 * @method static MoneyRange SVC(string $amount)
 * @method static MoneyRange SYP(string $amount)
 * @method static MoneyRange SZL(string $amount)
 * @method static MoneyRange THB(string $amount)
 * @method static MoneyRange TJS(string $amount)
 * @method static MoneyRange TMT(string $amount)
 * @method static MoneyRange TND(string $amount)
 * @method static MoneyRange TOP(string $amount)
 * @method static MoneyRange TRY(string $amount)
 * @method static MoneyRange TTD(string $amount)
 * @method static MoneyRange TWD(string $amount)
 * @method static MoneyRange TZS(string $amount)
 * @method static MoneyRange UAH(string $amount)
 * @method static MoneyRange UGX(string $amount)
 * @method static MoneyRange USD(string $amount)
 * @method static MoneyRange USN(string $amount)
 * @method static MoneyRange UYI(string $amount)
 * @method static MoneyRange UYU(string $amount)
 * @method static MoneyRange UZS(string $amount)
 * @method static MoneyRange VEF(string $amount)
 * @method static MoneyRange VND(string $amount)
 * @method static MoneyRange VUV(string $amount)
 * @method static MoneyRange WST(string $amount)
 * @method static MoneyRange XAF(string $amount)
 * @method static MoneyRange XAG(string $amount)
 * @method static MoneyRange XAU(string $amount)
 * @method static MoneyRange XBA(string $amount)
 * @method static MoneyRange XBB(string $amount)
 * @method static MoneyRange XBC(string $amount)
 * @method static MoneyRange XBD(string $amount)
 * @method static MoneyRange XBT(string $amount)
 * @method static MoneyRange XCD(string $amount)
 * @method static MoneyRange XDR(string $amount)
 * @method static MoneyRange XOF(string $amount)
 * @method static MoneyRange XPD(string $amount)
 * @method static MoneyRange XPF(string $amount)
 * @method static MoneyRange XPT(string $amount)
 * @method static MoneyRange XSU(string $amount)
 * @method static MoneyRange XTS(string $amount)
 * @method static MoneyRange XUA(string $amount)
 * @method static MoneyRange XXX(string $amount)
 * @method static MoneyRange YER(string $amount)
 * @method static MoneyRange ZAR(string $amount)
 * @method static MoneyRange ZMW(string $amount)
 * @method static MoneyRange ZWL(string $amount)
 */
trait MoneyRangeFactory
{
    /**
     * Convenience factory method for a MoneyRange object.
     *
     * <code>
     * $fiveToTenDollars = MoneyRange::USD(500, 1000);
     * </code>
     *
     * @param string $method
     * @param array  $arguments
     *
     * @return MoneyRange
     *
     * @throws \InvalidArgumentException If either amount is not integer(ish)
     */
    public static function __callStatic($method, $arguments)
    {
        return new MoneyRange(
            new Money($arguments[0], new Currency($method)),
            new Money($arguments[1], new Currency($method))
        );
    }
}
